# Generated by Django 3.2.5 on 2023-12-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maincategoryname', models.CharField(default='', max_length=70)),
                ('icon', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
