# Generated by Django 3.2.5 on 2024-01-12 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0002_alter_maincategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.maincategory')),
            ],
        ),
    ]
