# Generated by Django 3.2.5 on 2024-01-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0003_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='categoryid',
            new_name='maincategoryid',
        ),
    ]
