# Generated by Django 3.2.5 on 2024-01-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0004_rename_categoryid_subcategory_maincategoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
