# Generated by Django 3.2.5 on 2024-02-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsubname', models.CharField(default='', max_length=70)),
                ('productsubnamedescription', models.CharField(default='', max_length=500)),
                ('qty', models.IntegerField(default='')),
                ('price', models.IntegerField(default='')),
                ('color', models.CharField(default='', max_length=70)),
                ('size', models.CharField(default='', max_length=70)),
                ('offerprice', models.IntegerField(default='')),
                ('offertype', models.IntegerField(default='')),
                ('icon', models.ImageField(upload_to='static/')),
                ('brandid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.brand')),
                ('maincategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.maincategory')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.product')),
                ('subcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.subcategory')),
            ],
        ),
    ]
