# Generated by Django 3.2.5 on 2024-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0007_productdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='productsubnamedescription',
            new_name='productsubdescription',
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='offertype',
            field=models.CharField(default='', max_length=70),
        ),
    ]
