# Generated by Django 3.2.5 on 2024-02-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0008_auto_20240212_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='icon',
            field=models.TextField(default=''),
        ),
    ]
