# Generated by Django 3.2.5 on 2024-05-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0011_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('mobileno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('emailid', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(default='', max_length=70)),
                ('lastname', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=70)),
                ('dob', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=70)),
                ('city', models.CharField(default='', max_length=70)),
                ('postcode', models.CharField(default='', max_length=70)),
                ('mobileno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.users')),
            ],
        ),
    ]
